import { MOVE_TAB, SCALE_TAB, ROTATE_TAB } from './inner-tabs/innerTabImports';

export const PLACEMENT_TAB = {
  visible: true,
  label: 'PLACEMENT',
  content: {
    component: {
      style: {
        default: {
          display: 'flex',
          'align-item': 'center',
          'justify-content': 'end',
          'column-gap': '5px',
          padding: '8px',
        },
      },
      // classes: {
      //   main: 'placement-wrapper',
      //   btnMain: 'border-bottom',
      //   innerBtnMain: 'align-right mini-button-row',
      // },
      button: [
        {
          label: '',
          disabled: false,
          onClick: () => {},
          ref: 'placement_tab_buttons',
          schema_type: 'button',
          icon: 'zoom_out_map',
          ariaLabel: 'loadObjectFromQueue',
          tooltip: 'Add gaps between objects',
          mui: { type: 'mini_fab', color: 'primary' },
        },
        {
          label: '',
          disabled: false,
          onClick: () => {},
          ref: 'placement_tab_buttons',
          schema_type: 'button',
          icon: 'delete_forever',
          ariaLabel: 'removeObject',
          tooltip: 'Delete selected object',
          mui: { type: 'mini_fab', color: 'warn' },
        },
        {
          label: '',
          disabled: false,
          onClick: () => {},
          ref: 'placement_tab_buttons',
          schema_type: 'button',
          icon: 'library_add',
          ariaLabel: 'duplicateObject',
          tooltip: 'Duplicate selected object',
          mui: { type: 'mini_fab', color: 'primary' },
        },
        {
          label: '',
          disabled: false,
          onClick: () => {},
          ref: 'placement_tab_buttons',
          schema_type: 'button',
          icon: 'cloud_upload',
          ariaLabel: 'uploadObject',
          tooltip: 'Load objects from external source',
          mui: { type: 'mini_fab', color: 'primary' },
        },
        {
          label: '',
          disabled: false,
          onClick: () => {},
          ref: 'placement_tab_buttons',
          schema_type: 'button',
          icon: 'cloud_download',
          ariaLabel: 'loadObjectFromCloud',
          tooltip: 'Load objects from Cloud',
          mui: { type: 'mini_fab', color: 'primary' },
        },
        {
          label: '',
          disabled: false,
          onClick: () => {},
          ref: 'placement_tab_buttons',
          schema_type: 'button',
          icon: 'playlist_add',
          ariaLabel: 'loadObjectFromQueue',
          tooltip: 'Load objects from your queue',
          mui: { type: 'mini_fab', color: 'primary' },
        },
      ],
    },
    tabs: [MOVE_TAB, SCALE_TAB, ROTATE_TAB],
  },
};
