export const VISUALS: object = {
  component: {
    style: {
      default: {},
      plate_style: {
        // padding: '1em .5em 1em 1em',
        height: '94vh',
        // border: '1px solid rgba(0,0,0,0.12)',
        // border: '1px solid white',
        position: 'relative',
      },
      //   hot_key: {
      //     display: 'flex',
      //     position: 'absolute',
      //     left: '.8em',
      //     bottom: '.8em',
      //     p: {
      //       position: 'relative',
      //       'margin-bottom': 0,
      //       color: 'white',
      //       float: 'left',
      //       transform: 'skew(10deg)',
      //       background: 'transparentize($primary-color, .25)',
      //       'border-radius': '6px',
      //       padding: '.7em .5em',
      //       'margin-left': '.5em',
      //       'font-weight': 400,
      //       `&:first-chil {
      //         'margin-left': '0',
      //       }`,
      //     },
      //   },
    },
    controls: {
      camera: {
        visible: true,
        restricted: false,
        buttons: {
          controls: [
            {
              label: '',
              disabled: false,
              onClick: () => {},
              ref: 'canvas_camera_button',
              schema_type: 'button',
              icon: 'keyboard_arrow_left',
              ariaLabel: 'cameraLeft',
              tooltip: 'Rotate camera left',
              matTooltipPosition: 'below',
              mui: { type: 'mini_fab', color: 'primary' },
              style: {
                top: '0',
                left: '5%',
                // transform: 'translateX(-50%)',
              },
            },
            {
              label: '',
              disabled: false,
              onClick: () => {},
              ref: 'canvas_camera_button',
              schema_type: 'button',
              icon: 'keyboard_arrow_right',
              ariaLabel: 'cameraRight',
              tooltip: 'Rotate camera right',
              matTooltipPosition: 'right',
              mui: { type: 'mini_fab', color: 'primary' },
              style: {
                left: '50%',
                top: '80%',
                transform: 'translateY(-50%)',
              },
            },
            {
              label: '',
              disabled: false,
              onClick: () => {},
              ref: 'canvas_camera_button',
              schema_type: 'button',
              icon: 'play_for_work',
              ariaLabel: 'cameraDown',
              tooltip: 'Place object on the build plate',
              matTooltipPosition: 'below',
              matTooltipHideDelay: 100000,
              mui: { type: 'mini_fab', color: 'primary' },
              style: {
                'background-color': '#4285f4',
                top: '50%',
                left: '-18%',
                transform: 'translate(-50%, -50%)',
              },
            },
          ],
          zoom: [
            {
              label: '',
              disabled: false,
              onClick: () => {},
              ref: 'canvas_camera_button',
              schema_type: 'button',
              icon: 'add',
              ariaLabel: 'cameraDown',
              tooltip: 'Place object on the build plate',
              matTooltipPosition: 'below',
              matTooltipHideDelay: 100000,
              mui: { type: 'mini_fab', color: 'primary' },
            },
            {
              label: '',
              disabled: false,
              onClick: () => {},
              ref: 'canvas_camera_button',
              schema_type: 'button',
              icon: 'remove',
              ariaLabel: 'cameraDown',
              tooltip: 'Place object on the build plate',
              matTooltipPosition: 'below',
              matTooltipHideDelay: 100000,
              mui: { type: 'mini_fab', color: 'primary' },
            },
          ],
        },
      },
      toolbar: {
        visible: true,
        buttons: [
          {
            label: '',
            disabled: false,
            onClick: () => {},
            ref: 'canvas_toolbar_button',
            schema_type: 'button',
            icon: 'undo',
            ariaLabel: 'cameraDown',
            tooltip: 'Place object on the build plate',
            matTooltipPosition: 'below',
            matTooltipHideDelay: 100000,
            mui: { type: 'icon', color: 'primary' },
          },
          {
            label: '',
            disabled: false,
            onClick: () => {},
            ref: 'canvas_toolbar_button',
            schema_type: 'button',
            icon: 'auto_fix_high',
            ariaLabel: 'cameraDown',
            tooltip: 'Place object on the build plate',
            matTooltipPosition: 'below',
            matTooltipHideDelay: 100000,
            mui: { type: 'icon', color: 'primary' },
          },
          {
            label: '',
            disabled: false,
            onClick: () => {},
            ref: 'canvas_toolbar_button',
            schema_type: 'button',
            icon: 'system_update_alt',
            ariaLabel: 'cameraDown',
            tooltip: 'Place object on the build plate',
            matTooltipPosition: 'below',
            matTooltipHideDelay: 100000,
            mui: { type: 'icon', color: 'primary' },
          },
          {
            label: '',
            disabled: false,
            onClick: () => {},
            ref: 'canvas_toolbar_button',
            schema_type: 'button',
            icon: 'grid_view',
            ariaLabel: 'cameraDown',
            tooltip: 'Place object on the build plate',
            matTooltipPosition: 'below',
            matTooltipHideDelay: 100000,
            mui: { type: 'icon', color: 'primary' },
          },
          {
            label: '',
            disabled: false,
            onClick: () => {},
            ref: 'canvas_toolbar_button',
            schema_type: 'button',
            icon: 'tune',
            ariaLabel: 'cameraDown',
            tooltip: 'Place object on the build plate',
            matTooltipPosition: 'below',
            matTooltipHideDelay: 100000,
            mui: { type: 'icon', color: 'secondary' },
          },
          {
            label: '',
            disabled: false,
            onClick: () => {},
            ref: 'canvas_toolbar_button',
            schema_type: 'button',
            icon: 'system_update_alt',
            ariaLabel: 'cameraDown',
            tooltip: 'Place object on the build plate',
            matTooltipPosition: 'below',
            matTooltipHideDelay: 100000,
            mui: { type: 'icon', color: 'primary' },
          },
        ],
      },
      dimension: {
        visible: true,
        restricted: false,
        data: [
          {
            label: 'X:',
            value: 0,
            restricted: false,
          },
          {
            label: 'Y:',
            value: 0,
            restricted: false,
          },
          {
            label: 'Z:',
            value: 0,
            restricted: false,
          },
        ],
      },
    },
    hot_keys: { visible: true, data: ['W: MOVE', 'E: SCALE', 'R: ROTATE'] },
  },
};
